name: appsync
description: AppSync integration
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true
